jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    expired-time-ms: 3000000
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDR}:3306/HR_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 1000
  redis:
    #    lettuce:
    #      pool:
    #        max-active: 10
    #        max-idle: 10
    #        min-idle: 2
    host: localhost       # 추후 환경변수 처리
    port: 6379            # 추후 환경변수 처리
    password: 'qwer1234'  # 추후 환경변수 처리

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
