spring:
  datasource:
    url: jdbc:mysql://10.10.10.10/ttt
    username: kje
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

