
jwt:
  secret-key: ${JWT_SECRET_KEY}
  secret-key2: ${JWT_SECRET_KEY2}
  token:
    expired-time-ms: 100000000
  refresh-token:
    expired-time-ms: 3600000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDR}:3306/HR_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}



  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:

      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 1000
  redis:
    host: 10.104.183.84  # 마스터 서버 주소 (추후 쿠버네티스 클러스터 ip로 바꿔야함)
    port: 6379         # Redis 기본 포트
    password: qwer1234 # 설정된 패스워드

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
