spring:
  datasource:
    url: jdbc:mysql://10.10.10.10/ttt
    username: kje
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:

      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 1000
  redis:
    host: 10.10.10.10  # 마스터 서버 주소 (추후 쿠버네티스 클러스터 ip로 바꿔야함)
    port: 6379         # Redis 기본 포트
    password: qwer1234 # 설정된 패스워드


